(defun color-theme-eiel ()
  "Color theme by eiel, created 2011-04-27."
  (interactive)
  (color-theme-install
   '(color-theme-eiel
     ((background-color . "#222")
      (background-mode . dark)
      (border-color . "#111")
      (cursor-color . "#ff3319")
      (foreground-color . "#eee")
      (mouse-color . "#000"))
     (default ((t (:background "#222" :foreground "#eee"))))
     (region ((t (:background "#2F3F52"))))
     (highlight ((t (:background "#444"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t :slant italic))))
     (font-lock-comment-face ((t (:foreground "#686" :slant italic))))
     (font-lock-function-name-face ((t (:foreground "#77B5FF"))))
     (font-lock-type-face ((t (:foreground "#85FFDF"))))
     (font-lock-keyword-face ((t (:foreground "#66c8ef"))))
     (font-lock-string-face ((t (:foreground "#9aca7e" :background "#212A24"))))
     (font-lock-variable-name-face ((t (:foreground "#FFB14B"))))
     (fringe ((t (:foreground "#5D5A4B" :background "#333"))))
     (magit-diff-add ((t (:foreground "#9aca7e"))))
     (magit-item-highlight ((t (:inherit highlight))))
     (mode-line ((t (:background "#c6d6ff" :foreground "#000"))))
     (mode-line-inactive ((t (:background "#c3c3c3" :foreground "#000"))))
     (mumamo-background-chunk-submode1 ((t (:background "#2a322a"))))
     (show-paren-match ((t (:background "#2d2abb"))))
     )))
;; (color-theme-eiel)

(defun color-theme-xc ()
  "Color theme by eiel, created 2010-02-21."
  (interactive)
  (color-theme-install
   '(color-theme-xc
     ((background-color . "#fff")
      (background-mode . light)
      (border-color . "#111")
      (cursor-color . "#000")
      (foreground-color . "#000")
      (mouse-color . "#000"))
     (default ((t (:background "#fff" :foreground "#000"))))
     (region ((t (:background "#B5D5FF"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t :slant italic))))
     (font-lock-comment-face ((t (:foreground "#008516"))))
     (font-lock-builtin-face ((t (:foreground "#dd7b3b"))))
     (font-lock-constant-face ((t (:foreground "#723AA7"))))
     (font-lock-doc-string-face ((t (:foreground "#9b859d"))))
     (font-lock-function-name-face ((t (:foreground "#32595D"))))
     (font-lock-keyword-face ((t (:foreground "#BA23A0"))))
     (font-lock-preprocessor-face ((t (:foreground "#77482C"))))
     (font-lock-reference-face ((t (:foreground "8b98ab"))))
     (font-lock-string-face ((t (:foreground "#D0271B"))))
     (font-lock-type-face ((t (:foreground "#723AA7"))))
     (font-lock-variable-name-face ((t (:foreground "#508187"))))
     (font-lock-warning-face ((t (:bold t :background "#420e09" :foreground "#eeeeee"))))
     (mode-line ((t (:background "#aaa" :foreground "#000"))))
     (mode-line-inactive ((t (:background "#dfd" :foreground "#000"))))
     )))
;;; (color-theme-xc)

(defun color-theme-tl ()
  "Color theme by eiel, created 2010-02-21."
  (interactive)
  (color-theme-install
   '(color-theme-tm
     ((background-color . "#fff")
      (background-mode . light)
      (border-color . "#111")
      (cursor-color . "#9d9")
      (foreground-color . "#000")
      (mouse-color . "#030"))
     (default ((t (:background "#fff" :foreground "#000"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t :slant italic))))
     (font-lock-comment-face ((t (:foreground "#008516"))))
     (mode-line ((t (:background "#aea" :foreground "#000"))))
     (mode-line-inactive ((t (:background "#dfd" :foreground "#000"))))
     (fringe ((t (:background "#dfd" :foreground "#333"))))
     (show-paren-match ((t (:background "#ddf"))))
     (isearch ((t (:background "#046" :foreground "#fff"))))
     )))
;; (color-theme-tl)

(defun color-theme-tm ()
  "Color theme by dngpng, created 2007-09-11."
  (interactive)
  (color-theme-install
   '(color-theme-tm
     ((background-color . "#111")
      (background-mode . dark)
      (border-color . "#111")
      (cursor-color . "#663")
      (foreground-color . "#ddd")
      (mouse-color . "sienna1"))
     (default ((t (:background "#111" :foreground "#ddd"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t :slant italic))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "#111" :foreground "#ddd"))))
     (font-lock-builtin-face ((t (:foreground "#dd7b3b"))))
     (font-lock-comment-face ((t (:foreground "#9f9" ))))
     (font-lock-constant-face ((t (:foreground "#99cf50"))))
     (font-lock-doc-string-face ((t (:foreground "#9b859d"))))
     (font-lock-function-name-face ((t (:foreground "#e9c062" :bold t))))
     (font-lock-keyword-face ((t (:foreground "#cf6a4c" :bold t))))
     (font-lock-preprocessor-face ((t (:foreground "#aeaeae"))))
     (font-lock-reference-face ((t (:foreground "8b98ab"))))
     (font-lock-string-face ((t (:foreground "#65b042"))))
     (font-lock-type-face ((t (:foreground "#c5af75"))))
     (font-lock-variable-name-face ((t (:foreground "#3387cc"))))
     (font-lock-warning-face ((t (:bold t :background "#420e09" :foreground "#eeeeee"))))
     (erc-current-nick-face ((t (:foreground "#aeaeae"))))
     (erc-default-face ((t (:foreground "#ddd"))))
     (erc-keyword-face ((t (:foreground "#cf6a4c"))))
     (erc-notice-face ((t (:foreground "#666"))))
     (erc-timestamp-face ((t (:foreground "#65b042"))))
     (erc-underline-face ((t (:foreground "c5af75"))))
     (nxml-attribute-local-name-face ((t (:foreground "#3387cc"))))
     (nxml-attribute-colon-face ((t (:foreground "#e28964"))))
     (nxml-attribute-prefix-face ((t (:foreground "#cf6a4c"))))
     (nxml-attribute-value-face ((t (:foreground "#65b042"))))
     (nxml-attribute-value-delimiter-face ((t (:foreground "#99cf50"))))
     (nxml-namespace-attribute-prefix-face ((t (:foreground "#9b859d"))))
     (nxml-comment-content-face ((t (:foreground "#3a3"))))
     (nxml-comment-delimiter-face ((t (:foreground "#3a3"))))
     (nxml-element-local-name-face ((t (:foreground "#e9c062"))))
     (nxml-markup-declaration-delimiter-face ((t (:foreground "#aeaeae"))))
     (nxml-namespace-attribute-xmlns-face ((t (:foreground "#8b98ab"))))
     (nxml-prolog-keyword-face ((t (:foreground "#c5af75"))))
     (nxml-prolog-literal-content-face ((t (:foreground "#dad085"))))
     (nxml-tag-delimiter-face ((t (:foreground "#cda869"))))
     (nxml-tag-slash-face ((t (:foreground "#cda869"))))
     (nxml-text-face ((t (:foreground "#ddd"))))
     (gui-element ((t (:background "#0e2231" :foreground "black"))))
     (highlight ((t (:background "#4a410d"))))
     (highline-face ((t (:background "#4a410d"))))
     ;;     (hl-line ((t (:background "#4a410d"))))
     (hl-line ((t (:background "#000033"))))
     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (mmm-default-submode-face ((t (:background "#111"))))
     (mode-line ((t (:background "#e6e5e4" :foreground "black"))))
     (mumamo-background-chunk-major ((t (:background "#111"))))
     (mumamo-background-chunk-submode1 ((t (:background "#030"))))
     (outline-2 ((t (:foreground "SpringGreen2"))))
     (outline-3 ((t (:foreground "SkyBlue2" :inherit nil))))
     (primary-selection ((t (:background "#222"))))
     (region ((t (:background "#4a410d"))))
     (show-paren-match ((t (:background "#006666"))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (underline ((nil (:underline nil)))))))

(when window-system
  (my-require-and-when 'color-theme
    (color-theme-initialize)
    (color-theme-eiel)
    ;; (color-theme-tl)
    ;; (color-theme-xc)
    ))
