(require 'twittering-mode)
(setq twittering-username twitter-username)
(setq twittering-password twitter-password)
(twittering-icon-mode)
(setq twittering-timer-interval 120)
(setq twittering-status-format "%i %s(%S),  %@:\n%FILL{  %T // from %f%L%r%R}")
(setq twittering-retweet-format "RT @%s: %t")
(global-set-key "\C-cs" 'twittering-update-status-interactive)

(require 'twit)
(setq twit-pass twitter-password)
(setq twit-user twitter-username)
(setq twit-language 'ja)
(setq twit-show-user-images t)
(twit-set-auth twit-user twit-pass)
